/**
// example meat to FDA standards. Can be found on: http://www.foodsafety.gov/keep/charts/mintemp.html
// example meat temperatures below the FDA minimums can be found on: http://www.foodnetwork.com/recipes/articles/meat-and-poultry-temperature-guide.html
// Fahrenheit to Celsius can be found here: http://fahrenheittocelsius.com/
*/

module.exports = {
      "eggs": "The FDA recommends cooking egg dishes to one hundred and sixty degrees fahrenheit and seventy-one degrees celcius",
      "salmon": "The FDA recommends cooking salmon to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "fish": "The FDA recommends cooking fin fish to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "grouper": "The FDA recommends cooking grouper to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "mahi-mahi": "The FDA recommends cooking mahi-mahi to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "swordfish": "The FDA recommends cooking swordfish to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "herring": "The FDA recommends cooking herring to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "trout": "The FDA recommends cooking trout to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "catfish": "The FDA recommends cooking catfish to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "rohu": "The FDA recommends cooking rohu to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "tuna": "The FDA recommends cooking tuna to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "halibut": "The FDA recommends cooking halibut to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "tilapia": "The FDA recommends cooking tilapia to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "cod": "The FDA recommends cooking cod to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius or until the flesh is opaque and seperates easily with a fork",
      "scallops": "The FDA recommends cooking scallops until the flesh is milky white or opaque and firm",
      "crab": "The FDA recommends cooking crab until the flesh is pearly and opaque",
      "lobster": "The FDA recommends cooking lobster until the flesh is pearly and opaque",
      "shrimp": "The FDA recommends cooking shrimp until the flesh is pearly and opaque",
      "mussels": "The FDA recommends cooking mussels until the shells open during cooking",
      "oysters": "The FDA recommends cooking clams until the shells open during cooking",
      "clams": "The FDA recommends cooking clams until the shells open during cooking",
      "duck": "The FDA recommends cooking duck to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "goose": "The FDA recommends cooking goose to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "stuffing": "The FDA recommends cooking stuffing to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "chicken breast": "The FDA recommends cooking chicken breast to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "chicken": "The FDA recommends cooking whole chicken to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "turkey breast": "The FDA recommends cooking turkey breast to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "turkey": "The FDA recommends cooking whole turkey to one hundred and sixty-five degrees fahrenheit and seventy-four degrees celcius",
      "veal": "The FDA recommends cooking veal to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "goat": "The FDA recommends cooking goat to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "goat chops": "The FDA recommends cooking goat chops to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "goat steak": "The FDA recommends cooking goat steak to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "goat roast": "The FDA recommends cooking goat roast to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "lamb chops": "The FDA recommends cooking lamb chops to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "pork chops": "The FDA recommends cooking pork chops to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "lamb": "The FDA recommends cooking Lamb to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rump roast": "The FDA recommends cooking Roast to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "roast": "The FDA recommends cooking Roast to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "ham": "The FDA recommends cooking fresh ham to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "pork": "The FDA recommends cooking fresh pork to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "steak rare": "The internal temperature for a steak cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "steak medium rare": "The internal temperature for a steak cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "steak medium": "The internal temperature for a steak cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "steak medium well": "The internal temperature for a steak cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "steak well done": "The internal temperature for a steak cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "steak": "The FDA recommends cooking steak to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rare steak": "The internal temperature for a steak cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "medium rare steak": "The internal temperature for a steak cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "medium steak": "The internal temperature for a steak cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "medium well steak": "The internal temperature for a steak cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "well done steak": "The internal temperature for a steak cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "beef rare": "The internal temperature for beef cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "beef medium rare": "The internal temperature for beef cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "beef medium": "The internal temperature for beef cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "beef medium well": "The internal temperature for beef cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "beef well done": "The internal temperature for beef cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "beef": "The FDA recommends cooking beef to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rare beef": "The internal temperature for beef cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "medium rare beef": "The internal temperature for beef cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "medium beef": "The internal temperature for beef cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "medium well beef": "The internal temperature for beef cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "well done beef": "The internal temperature for beef cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "venison rare": "The internal temperature for a venison cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "venison medium rare": "The internal temperature for a venison cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "venison medium": "The internal temperature for a venison cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "venison medium well": "The internal temperature for a venison cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "venison well done": "The internal temperature for a venison cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "venison": "The FDA recommends cooking venison to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rare venison": "The internal temperature for a venison cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "medium rare venison": "The internal temperature for a venison cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "medium venison": "The internal temperature for a venison cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "medium well venison": "The internal temperature for a venison cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "well done venison": "The internal temperature for a venison cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "elk rare": "The internal temperature for a elk cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "elk medium rare": "The internal temperature for a elk cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "elk medium": "The internal temperature for a elk cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "elk medium well": "The internal temperature for a elk cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "elk well done": "The internal temperature for a elk cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "elk": "The FDA recommends cooking elk to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rare elk": "The internal temperature for a elk cooked rare is one hundred and twenty five degrees fahrenheit and fifty two degrees celcius.",
      "medium rare elk": "The internal temperature for a elk cooked medium rare is one hundred and thirty degrees fahrenheit and fifty four degrees celcius.",
      "medium elk": "The internal temperature for a elk cooked medium is one hundred and thirty five degrees fahrenheit and fifty seven degrees celcius.",
      "medium well elk": "The internal temperature for a elk cooked medium well is one hundred and forty five degrees fahrenheit and sixty three degrees celcius.",
      "well done elk": "The internal temperature for a elk cooked well done is one hundred and sixty degrees fahrenheit and seventy one degrees celcius.",
      "caribou": "The FDA recommends cooking caribou to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "moose": "The FDA recommends cooking moose to one hundred and forty-five degrees fahrenheit and sixty-three degrees celcius with a three minute rest time",
      "rabbit": "The internal temperature for a rabbit is one hundred and sixty degrees fahrenheit and seventy one degrees celcius",
      "burger": "The internal temperature for a burger is one hundred and sixty degrees fahrenheit and seventy one degrees celcius",
      "hamburger": "The internal temperature for a hamburger is one hundred and sixty degrees fahrenheit and seventy one degrees celcius",
      "hot dog": "Hot dogs should be heated until steaming hot and kept at one hundred and forty degrees fahrenheit or warmer and sixy degrees celcius or warmer",
      "hot dogs": "Hot dogs should be heated until steaming hot and kept at one hundred and forty degrees fahrenheit or warmer and sixy degrees celcius or warmer",
  };
